### ISSUE TITLE
Sonic-Mgmt WeChat group

### ISSUE THREAD

**Issue by feng891005** [Azure/sonic-mgmt#1519]
Hello everyone, in order to facilitate communication, I created a WeChat discussion group about the Sonic-mgmt project, 
Welcome everyone to join!!!

**Comment by lguohan** [comment]
joined!

**Comment by lguohan** [comment]
can we get a group id and then we can add README.md?

**Comment by feng891005** [comment]
> can we get a group id and then we can add README.md? it seems that the group is expired on 4/8?
Yes, but unfortunately WeChat group does not have a fixed id, but we can fix a link externally, I will update this picture regularly

Fix link:  http://www.xbtao.com/sonic_wechat_group/sonic-mgmt.jpg

**Comment by li7hui** [comment]
Dear All,
Since the Wechat group id expires every 7 days. You can add my Wechat ID, which is "18830245264", and indicate that you want to join the Sonic-mgmt Wechat group, I will pull you into the group. 
@lguohan  You can put my Wechat ID, "18830245264" in the README.md, and I will maintain this task regularly.
