### ISSUE TITLE
vrf test could leave system in broken state and hard to recover

### ISSUE THREAD

**Issue by yxieca** [Azure/sonic-mgmt#1641]
**Description**

**Steps to reproduce the issue:**
1. run vrf test
2.
3.

**Describe the results you received:**
test pass or fail, but leave dut in healthy state (or the state test case entered with)

**Describe the results you expected:**
when test fails, the system is broken. interfaces/lag/bgp are down. config reload will cause management IP to disappear too.

Following code was the culprit. Looks like vrf test backed up the good config_db.json, but if the test failed between the first line and second line of the grep result, the system will be left with a config_db intended for test but not the healthy original config_db.json.

tests/test_vrf.py:    duthost.shell("mv /etc/sonic/config_db.json /etc/sonic/config_db.json.bak")
tests/test_vrf.py:    duthost.shell("cp /etc/sonic/config_db.json.bak /etc/sonic/config_db.json")
tests/test_vrf.py:    duthost.shell("rm /etc/sonic/config_db.json.bak")

Test author need to add protection code to restore system no matter what exiting path the test takes.

**Comment by yxieca** [comment]
@dawnbeauty can you look into this issue please?

**Comment by daall** [comment]
@yxieca is this addressed with your auto-recovery improvements or do we still need action from @dawnbeauty?

**Comment by dawnbeauty** [comment]
@yieca vrf tests is intend to cleanup vrf cfg and recover as you described. 
It is done by fixture `setup_vrf`(include teardown code).  Note that if an exception happens during the setup code (before the yield keyword), the teardown code (after the yield) will not be called.
So i think maybe something goes wrong when setup_vrf but not test failed.

Could you show me your detail test results?  Or use option --setup-show to check if the setup_vrf works during SETUP.  For example:
```
root@sonic-mgmt:/var/root/sonic-mgmt-vrf/tests# py.test  -vvv --inventory veos --host-pattern all --user admin --testbed vms-t0 --testbed_file testbed.csv  --duration=0 --log-cli-level INFO --setup-show --show-capture=stdout  --vrf_capacity 1000 --vrf_test_count 100 test_vrf.py::TestVrfCapacity
============================ test session starts ==========================================
...<omitted outputs>
                                                                                                            
test_vrf.py::TestVrfCapacity::test_ping 
SETUP    S localhost
------------------------------ live log setup -----------------------------------------------
INFO     root:conftest.py:102 <SubRequest 'localhost' for <Function test_ping>> used time: 0.09s

SETUP    S testbedINFO     root:conftest.py:102 <SubRequest 'testbed' for <Function test_ping>> used time: 0.00s
    SETUP    M ansible_adhocINFO     root:conftest.py:102 <SubRequest 'ansible_adhoc' for <Function test_ping>> used time: 0.00s
    SETUP    M duthost (fixtures used: ansible_adhoc, testbed)INFO     root:conftest.py:102 <SubRequest 'duthost' for <Function test_ping>> used time: 0.01s
    SETUP    M ptfhost (fixtures used: ansible_adhoc, testbed)INFO     root:conftest.py:102 <SubRequest 'ptfhost' for <Function test_ping>> used time: 0.01s
    SETUP    M host_facts (fixtures used: duthost)INFO     root:conftest.py:102 <SubRequest 'host_facts' for <Function test_ping>> used time: 0.93s
>>>>>    SETUP    M setup_vrf (fixtures used: duthost, host_facts, ptfhost, testbed)INFO     root:conftest.py:102 <SubRequest 'setup_vrf' for <Function test_ping>> used time: 12.25s
    SETUP    M cfg_facts (fixtures used: duthost)INFO     root:conftest.py:102 <SubRequest 'cfg_facts' for <Function test_ping>> used time: 0.50s
      SETUP    C vrf_countINFO     root:conftest.py:102 <SubRequest 'vrf_count' for <Function test_ping>> used time: 0.00s
      SETUP    C random_vrf_list (fixtures used: vrf_count)INFO     root:conftest.py:102 <SubRequest 'random_vrf_list' for <Function test_ping>> used time: 0.00s
      SETUP    C setup_vrf_capacity (fixtures used: cfg_facts, duthost, ptfhost, random_vrf_list, vrf_count)INFO     root:conftest.py:102 <SubRequest 'setup_vrf_capacity' for <Function test_ping>> used time: 382.70s
        test_vrf.py::TestVrfCapacity::test_ping (fixtures used: ansible_adhoc, cfg_facts, duthost, host_facts, localhost, ptfhost, random_vrf_list, setup_vrf, setup_vrf_capacity, testbed, vrf_count)PASSED
        test_vrf.py::TestVrfCapacity::test_ip_fwd (fixtures used: ansible_adhoc, cfg_facts, duthost, host_facts, localhost, ptfhost, random_vrf_list, setup_vrf, setup_vrf_capacity, testbed, vrf_count)PASSED
      TEARDOWN C setup_vrf_capacity
      TEARDOWN C random_vrf_list
      TEARDOWN C vrf_count
    TEARDOWN M cfg_facts
>>>>>>    TEARDOWN M setup_vrf
...<omitted outputs>
```

An alternative option for executing the teardown code is to use the `addfinalizer` method of the `request-context` object to register finalization functions.  Of course, if an exception happens before the `addfinalizer` then it will not be executed.

So, I think we should figure out the root cause before we change the code. After that, we could choose a better way to cleanup.

**Comment by yxieca** [comment]
@dawnbeauty sure. will do.

**Comment by wangxin** [comment]
@dawnbeauty I investigated the issue and found that the setup_vrf fixture was executed. The problem is that setup_vrf fixture need to reboot the SONiC device with a new /etc/sonic/config_db.json which has vrf configurations. However, because the reboot function called by setup_vrf has issue, the SONiC device was not actually rebooted.

The detailed steps of how the issue happens:

* The setup_vrf fixture calls setup_vrf_cfg function.
* The setup_vrf_cfg function executes these major steps:
```
    # backup config_db.json
    duthost.shell("mv /etc/sonic/config_db.json /etc/sonic/config_db.json.bak")

    duthost.template(src="vrf/vrf_config_db.j2", dest="/tmp/config_db_vrf.json")
    duthost.shell("cp /tmp/config_db_vrf.json /etc/sonic/config_db.json")

    # FIXME use a better way to load config
    reboot(duthost, localhost)
```

* The last step is to reboot the SONiC device. However, the reboot function has issue and the SONiC device would not be actually rebooted.
* Then setup_vrf tries to get some data from the running config, assuming that the running config contains vrf related configurations. But indeed the running config is still the original one and does not contain vrf related configurations. Consequently below code in setup_vrf will fail with `KeyError: 'vrf_name'`

```
g_vars['vlan_peer_ips'], g_vars['vlan_peer_vrf2ns_map'] = setup_vlan_peer(duthost, ptfhost, cfg_facts)
```

* Because the exception in setup_vrf is raised before the `yield` statement, all the code after `yield` will not be executed. The /etc/sonic/config_db.json fill will still the one that has vrf configuration.

To fix the issue, I suggest you to use `common/reboot.py::reboot` to reboot the SONiC device.

**Comment by dawnbeauty** [comment]
@wangxin, thanks for the info. I'll double check the reboot function.
