### ISSUE TITLE
`gen-mg` is broken

### ISSUE THREAD

**Issue by qiluo-msft** [Azure/sonic-mgmt#3056]
**Description**
`gen-mg` is broken
```
$ ./testbed-cli.sh gen-mg vms-sn2700-t0 lab password.txt -vv
fatal: [str-msn2700-01 -> localhost]: FAILED! => {"changed": false, "msg": "failed to find the correct port config for Mellanox-SN2700-D40C8S8Something wrong when trying to find the portmap file, either the hwsku is not available or file location is not correct"}
```

However, changed to `deploy-mg` everything is working
```
$ ./testbed-cli.sh deploy-mg vms-sn2700-t0 lab password.txt -vv
```

**Steps to reproduce the issue:**
1.
2.
3.

**Describe the results you received:**

**Describe the results you expected:**

**Additional information you deem important:**

    **Output of `show version`:**

    ```
    (paste your output here)
    ```

    **Attach debug file `sudo generate_dump`:**

    ```
    (paste your output here)
    ```

**Comment by stephengzh** [comment]
Try to rewrite ansible/library/port_alias.py file around line 189:
filename = os.path.join(FILE_PATH,PORTMAP_FILE)

I use this method to obtain port_config.ini in deploy-mg. 

Addition:
The original "filename =  self.get_portconfig_path(asic_id)" in "deploy-mg" appears an error same as yours  in my deployment.
 
When I use "filename = os.path.join(FILE_PATH,PORTMAP_FILE)" in "gen-mg" appears another error:
msg": "IO error[Errno 2] No such file or directory: '/usr/share/sonic/device/x86_64-ruijie_b6510-48vs8cq-r0/B6510-48VS8CQ/port_config.ini'"

But this file can be found on my DUT.

**Comment by stephengzh** [comment]
Why did I rewrite?

Long time ago, maybe 6 months before, I can only remember the result of the filename is not on DUT. The directory and files are correct, but using filename = self.get_portconfig_path(asic_id), it pointed to another device, maybe sonic-mgmt, maybe server, but not DUT, when I rewrite the filename definition, it works. Maybe we should focus on which function calls the resulting self.get_portconfig_path(asic_id).

**Comment by lguohan** [comment]
try test-mg

**Comment by wangxin** [comment]
`gen-mg` will try to get port_config ini of the new HWSKU`Mellanox-SN2700-D40C8S8` locally from the sonic-mgmt docker container. It expects to find port_config.ini file at `/usr/share/sonic/device/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D40C8S8\port_config.ini` in sonic-mgmt docker.
`deploy-mg` instead will try to get `port_config.ini` remotely from DUT.
Since `Mellanox-SN2700-D40C8S8` is a newly added HWSKU, it is not available in the sonic-mgmt docker your were using. That's why `gen-mg` was not working but `deploy-mg` was fine.

Please update your sonic-mgmt docker image to the latest and try again. In sonic-mgmt docker based on latest image, the port_config.ini file is there.

```
johnar@08e3e810dc9f:~$ ls /usr/share/sonic/device/x86_64-mlnx_msn2700-r0/Mellanox-SN2700-D40C8S8
buffers.json.j2  buffers_defaults_t0.j2  buffers_defaults_t1.j2  hwsku.json  pg_profile_lookup.ini  port_config.ini  qos.json.j2  sai.profile  sai_2700_8x100g_40x50g_8x10g.xml
```
